FROM node:14-bullseye-slim
RUN npm install --global serverless@2.60.2
RUN npm install --global jest@27.2.4
RUN mkdir -p /root/dash-serverless-workshop
WORKDIR /root/dash-serverless-workshop
ENTRYPOINT [ "/bin/bash" ]